name: such deploy
on:
  push:
    branches: [ main ]

jobs:
  deployetto:
    runs-on: ubuntu-latest
    environment: tenco
    steps:
      - uses: actions/checkout@v2
      - name: push master branch to binary cache
        if: github.ref != 'refs/heads/main'
        env:
          SCRT: ${{ secrets.fake }}
        run: echo "Something very secret is ${SCRT}"
      - name: use env secrets
        env:
          SCRT: ${{ secrets.boss }}
        run: echo "Something very secret is $SCRT"
