name: such deploy
on:
  push:
    branches: [ main ]

jobs:
  deployetto:
    runs-on: ubuntu-latest
    environment: tenco
    steps:
      - uses: actions/checkout@v2
      - name: push master branch to binary cache
        if: github.ref != 'refs/heads/main'
        run: echo "Something very secret is ${{ secrets.fake }}"
      - name: use env secrets
        run: echo "environment secret ${{ secrets.boss }}"
